[MFLOG|0|2022-05-27T14:33:16.163828Z|runtime|1173e7cd-df2e-4c38-924e-254447999943]2022-05-27 16:33:16.163704: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
[MFLOG|0|2022-05-27T14:33:17.946511Z|runtime|2faf608f-65cb-4fd7-b17c-af381f924712]2022-05-27 16:33:16.163744: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[MFLOG|0|2022-05-27T14:33:17.946854Z|runtime|5050dd25-6a4b-4be3-9bb7-538e1bc58fc9]<flow FitFlow step data_process> failed:
[MFLOG|0|2022-05-27T14:33:18.366006Z|runtime|e206b7fa-c154-4a63-94ca-c6198c597ac8]    Internal error
[MFLOG|0|2022-05-27T14:33:18.367801Z|runtime|e241d9c3-ad5b-41ea-a466-c6d6d4d6245d]Traceback (most recent call last):
[MFLOG|0|2022-05-27T14:33:18.368084Z|runtime|f24e4949-36a6-42a3-8178-22f0c71062a9]  File "/home/nicolas_bzrd/Multi-Video-Temporal-Synchronization/lib/python3.8/site-packages/metaflow/cli.py", line 1101, in main
[MFLOG|0|2022-05-27T14:33:18.368238Z|runtime|c2eec78d-bd00-4159-b91e-e4ee0f6ab334]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2022-05-27T14:33:18.368448Z|runtime|69b599ff-94e5-43fd-b927-738d1d75e192]  File "/home/nicolas_bzrd/Multi-Video-Temporal-Synchronization/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2022-05-27T14:33:18.368690Z|runtime|91175c73-0594-4da0-92cd-9b876e193af0]    return self.main(args, kwargs)
[MFLOG|0|2022-05-27T14:33:18.368874Z|runtime|b770b338-606a-4e67-9919-6363310f2ec9]  File "/home/nicolas_bzrd/Multi-Video-Temporal-Synchronization/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2022-05-27T14:33:18.369034Z|runtime|90914c70-0fec-4489-8042-c2413eb19e43]    rv = self.invoke(ctx)
[MFLOG|0|2022-05-27T14:33:18.369231Z|runtime|0f1aad83-0d2a-4093-8184-3c711d44aef6]  File "/home/nicolas_bzrd/Multi-Video-Temporal-Synchronization/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
[MFLOG|0|2022-05-27T14:33:18.369379Z|runtime|3300bc7f-72ee-4300-995b-b68df7eb20fb]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2022-05-27T14:33:18.369566Z|runtime|f4804f30-27b4-4354-9689-c1bc7e31e444]  File "/home/nicolas_bzrd/Multi-Video-Temporal-Synchronization/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2022-05-27T14:33:18.369765Z|runtime|e10279e1-8816-4b41-b5b4-19d18a2c6324]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2022-05-27T14:33:18.369960Z|runtime|78013a30-71de-4125-9fec-6beab5a2227e]  File "/home/nicolas_bzrd/Multi-Video-Temporal-Synchronization/lib/python3.8/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2022-05-27T14:33:18.370158Z|runtime|36c1bfa5-d77f-482f-8262-c1440ab47246]    return callback(args, kwargs)
[MFLOG|0|2022-05-27T14:33:18.681310Z|runtime|88edffb7-2633-494f-8288-450185d439d0]  File "/home/nicolas_bzrd/Multi-Video-Temporal-Synchronization/lib/python3.8/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2022-05-27T14:33:18.681582Z|runtime|ffef9965-dbf3-4ef6-867f-bcfac21e3974]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2022-05-27T14:33:18.681753Z|runtime|61ad1f89-0cdb-4dc6-aad8-f8bc088a144f]  File "/home/nicolas_bzrd/Multi-Video-Temporal-Synchronization/lib/python3.8/site-packages/metaflow/cli.py", line 556, in step
[MFLOG|0|2022-05-27T14:33:18.681871Z|runtime|9fa67ad4-45af-4caa-bac5-3e7854a5fe28]    task.run_step(
[MFLOG|0|2022-05-27T14:33:18.682009Z|runtime|c748f2b2-598f-4510-890c-1ba2f6d777a8]  File "/home/nicolas_bzrd/Multi-Video-Temporal-Synchronization/lib/python3.8/site-packages/metaflow/task.py", line 554, in run_step
[MFLOG|0|2022-05-27T14:33:18.682144Z|runtime|6ac98987-b941-44ff-9285-aaf71b0bac30]    self._exec_step_function(step_func)
[MFLOG|0|2022-05-27T14:33:18.682269Z|runtime|91016622-31bb-4620-ba7b-810b1d4565c3]  File "/home/nicolas_bzrd/Multi-Video-Temporal-Synchronization/lib/python3.8/site-packages/metaflow/task.py", line 53, in _exec_step_function
[MFLOG|0|2022-05-27T14:33:18.682406Z|runtime|2d01f013-e322-4fd9-9f61-add4925af061]    step_function()
[MFLOG|0|2022-05-27T14:33:18.682592Z|runtime|b5ace212-ddd8-42b8-a5bb-4e4ad4011dfb]  File "Siamese_CNN_model__identical_image.py", line 13, in data_process
[MFLOG|0|2022-05-27T14:33:18.682734Z|runtime|b949a4e0-2826-475d-be0d-60ef85ff4f1a]    print('the data artifact is: %s' % self.my_var)
[MFLOG|0|2022-05-27T14:33:18.682877Z|runtime|ae10b4af-a31d-475e-814d-2d8d75b9a841]  File "/home/nicolas_bzrd/Multi-Video-Temporal-Synchronization/lib/python3.8/site-packages/metaflow/flowspec.py", line 223, in __getattr__
[MFLOG|0|2022-05-27T14:33:18.683013Z|runtime|ef97c415-1ae3-412c-b804-d1db96fd3a30]    raise AttributeError("Flow %s has no attribute '%s'" % (self.name, name))
[MFLOG|0|2022-05-27T14:33:18.683158Z|runtime|a7a2ecfb-1138-48fc-ae8a-d6a7db9bea4e]AttributeError: Flow FitFlow has no attribute 'my_var'
[MFLOG|0|2022-05-27T14:33:18.683338Z|runtime|db07189b-2b10-4b56-b7ad-3394d6a00591]
[MFLOG|0|2022-05-27T14:33:18.695327Z|runtime|a0cd3e63-5c28-46db-bab4-c738f7b47999]Task failed.